#
# Run kubeadm on a secondary master
#
---

- name: Run 'kubeadm' if this master node is also an etcd node (need to ignore two preflight errors here)
  command: kubeadm init --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Port-10250 --config=/root/kubeadm-init.yaml
  when: "master == inventory_hostname and master in groups['etcd']"

- name: Run 'kubeadm' if this master node is not an etcd node (all preflight errors active here)
  command: kubeadm init --config=/root/kubeadm-init.yaml
  when: "master == inventory_hostname and master not in groups['etcd']"
