#
# Sets up the admin user and account
#
---

- name: Create directory
  file: path=/root/setup/admin-user owner=root group=root mode=0755 state=directory

- name: Copy service-account.yaml
  copy: src=service-account.yaml dest=/root/setup/admin-user/service-account.yaml owner=root group=root mode=0644

- name: Copy admin-user.yaml
  copy: src=admin-user.yaml dest=/root/setup/admin-user/admin-user.yaml owner=root group=root mode=0644

- name: Install service account
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl apply -f /root/setup/admin-user/service-account.yaml

- name: Install admin user
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl apply -f /root/setup/admin-user/admin-user.yaml

-
