#
# Uninstall Elasticsearch
#
---

- name: Uninstall Curator job
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl delete -f curator-configmap.yaml -f curator-cronjob.yaml"
  args:
    chdir: /root/setup/elasticsearch

- name: Uninstall Elasticsearch services, accounts and deployments
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl delete -f es-serviceaccount.yaml -f es-discovery-service.yaml -f es-master-deployment.yaml -f es-client-service.yaml -f es-client-deployment.yaml -f es-data-service.yaml -f es-data-statefulset-hot.yaml -f es-data-statefulset-warm.yaml"
  args:
    chdir: /root/setup/elasticsearch

- name: Uninstall Elasticsearch persistent volume claims
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl -n kube-system delete persistentvolumeclaim `kubectl -n kube-system get pvc | awk '{ print $1 }' | egrep 'storage-elasticsearch-logging-data-(hot|warm)-[0-9]+'`"

- name: Uninstall Elasticsearch persistent volumes
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl -n kube-system delete persistentvolume `kubectl -n kube-system get pv | awk '{ print $1 }' | egrep 'elasticsearch-logging-data-[0-9]+'`"

