#
# Upgrade a cluster's masters:
# - get and install kubeadm binary in the target version
# - for all masters (one by one):
#   * shut down keepalived
#   * upgrade cluster using kubeadm
#   * start keepalived
#
---

- name: Make sure some needed software is installed via package manager
  package: name=kubeadm-{{ KUBERNETES_VERSION }} state=present

- name: Upgrade masters one by one
  include_tasks: upgrade-master.yaml
  with_items: "{{ groups['masters'] }}"
  loop_control:
    loop_var: master

- name: Upgrade software
  package: name={{ item }} state=present
  with_items:
  - kubelet-{{ KUBERNETES_VERSION }}
  - kubectl-{{ KUBERNETES_VERSION }}
  - kubernetes-cni-{{ KUBERNETES_CNI_VERSION }}

- name: Restart kubelet
  systemd: name=kubelet daemon_reload=true state=restarted 

- name: Set coredns replicas (just in case)
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl scale --replicas={{ groups['masters'] | length }} -n kube-system deployment/coredns"
  when: "'primary_master' in group_names"
