#
# Upgrades a single master.
#
---

- name: Create script for running upgrade with retries
  template: src=upgrade-with-retries.sh.j2 dest=/root/upgrade-with-retries.sh mode=0755
  when: "master == inventory_hostname"

- name: Perform upgrade with retries on master
  shell: "/root/upgrade-with-retries.sh 2>&1 | tee /tmp/upgrade.log; exit ${PIPESTATUS[0]}"
  when: "master == inventory_hostname"

- name: Create script for waiting for master
  local_action: "template src=wait-for-single-master.sh.j2 dest=/tmp/wait-for-master-{{ inventory_hostname }}.sh mode=0755"
  when: "master == inventory_hostname"

- name: Wait for master
  script: "/tmp/wait-for-master-{{ inventory_hostname }}.sh"
  when: "master == inventory_hostname"

