#
# Set up Fluentd to collect logs for Elasticsearch
#
---
- name: Create directory for Fluentd installation
  file: "path=/root/setup/fluentd mode=0755 state=directory"

- name: Copy Fluentd yaml files
  copy: "src={{ item }} dest=/root/setup/fluentd/"
  with_items:
  - fluentd-es-configmap.yaml
  - fluentd-es-ds.yaml
  - fluentd-es-serviceaccount.yaml

- name: Install Fluentd
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl create -f /root/setup/fluentd/"
