#
# Configure NGINX for the masters.
#
---
- name: Create configuration directory
  file: path=/etc/nginx state=directory owner=root mode=0755

- name: Generate service configuraton file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Generate static pod configuraton file directory
  file: path=/etc/kubernetes/manifests state=directory

- name: Generate static pod configuraton file
  template: src=nginx.yaml.j2 dest=/etc/kubernetes/manifests/nginx.yaml

