apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging-client
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch-Logging-Client"
    role: client
spec:
  selector:
    k8s-app: elasticsearch-logging
    role: client
  ports:
  - name: http
    port: 9200
    targetPort: 9200
#    nodePort: 30920
#  type: nodePort
#type: LoadBalancer
