apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging-data
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    role: data
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch-Logging-Client"
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    k8s-app: elasticsearch-logging
    role: data
