apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch-Discovery"
    role: master
spec:
  selector:
    k8s-app: elasticsearch-logging
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
