#
# Playbook to set up a Kubernetes cluster.
#
--- 

- name: Uninstall Cluster
  hosts: nodes
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - uninstall
  tags:
  - uninstall-cluster

- name: Reboot Cluster
  hosts: nodes
  remote_user: root
  gather_facts: no
  any_errors_fatal: no
  tasks:
  - name: Reboot machine
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
  tags:
  - reboot-cluster


