#
# Playbook to set up a Kubernetes cluster.
#
--- 
- name: Prepare Nodes
  hosts: nodes
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - prepare-nodes
  tags:
  - prepare-nodes

- name: Kube-VIP
  hosts: masters
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - {role: kube-vip, when: "LOAD_BALANCING == 'kube-vip'" }
  tags:
  - kube-vip

- name: Keepalived
  hosts: masters
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - {role: keepalived, when: "LOAD_BALANCING == 'nginx'" }
  tags:
  - keepalived

- name: NGINX
  hosts: masters
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - {role: nginx, when: "LOAD_BALANCING == 'nginx'" }
  tags:
  - nginx

- name: Deploy external etcd
  hosts: etcd
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - {role: external-etcd, when: "ETCD_HOSTING == 'external'" }
  tags:
  - external-etcd

- name: Set up primary master
  hosts: primary_master
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - primary-master
  - network-plugin
  tags:
  - masters
  - primary-master

- name: Set up secondary masters
  hosts: secondary_masters
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - secondary-masters
  tags:
  - masters
  - secondary-masters

- name: Make some adjustments for HA
  hosts: masters
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - ha-settings
  tags:
  - ha-settings
  - masters

- name: Create join token
  hosts: primary_master
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - join-token
  tags:
  - join-token
  - minions

- name: Join minions
  hosts: minions
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - minions
  tags:
  - join-minions
  - minions

- name: Label minions
  hosts: nodes
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - {role: label-minions, when: "'primary_master' in group_names" }
  tags:
  - label-minions
  - minions

- name: Create Admin Account
  hosts: primary_master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - admin-account
  tags:
  - admin-account
