#
# Playbook to set up a Kubernetes cluster.
#
--- 
- name: Prepare Nodes
  hosts: nodes
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - prepare-nodes
  tags:
  - prepare-nodes

- name: Deploy etcd
  hosts: etcd
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - etcd
  tags:
  - etcd

- name: HA
  hosts: masters
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - keepalived
  tags:
  - ha

- name: Set up masters
  hosts: masters
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - {role: client-certs,       when: "'masters'           in group_names" }
  - {role: primary-master,     when: "'primary-master'    in group_names" }
  - {role: secondary-masters,  when: "'secondary-masters' in group_names" }
  - {role: network-plugin,     when: "'primary-master'    in group_names" }
  - {role: ha-settings,        when: "'masters'           in group_names" }
  tags:
  - masters

- name: Set up minions
  hosts: nodes
  remote_user: root
  gather_facts: yes
  any_errors_fatal: yes
  roles:
  - {role: disable-scheduling, when: "'primary-master'    in group_names" }
  - {role: join-token,         when: "'primary-master'    in group_names" }
  - {role: minions,            when: "'minions'           in group_names" }
  - {role: enable-scheduling,  when: "'primary-master'    in group_names" }
  tags:
  - minions

- name: Label minions
  hosts: nodes
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - {role: label-minions,      when: "'primary-master'    in group_names" }
  tags:
  - label
