#
# Playbook to set up etcd operator.
#
--- 

- name: Set up etcd operator
  hosts: masters
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  roles:
  - {role: etcd-operator,      when: "'primary_master'    in group_names" }
  tags:
  - etcd-operator

