#
# Playbook to uninstall the EFK stack
#
---

- name: Uninstall Kibana
  hosts: primary-master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - import_tasks: roles/kibana/tasks/uninstall.yaml
  tags:
  - uninstall-kibana

- name: Uninstall Elasticsearch
  hosts: primary-master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - import_tasks: roles/elasticsearch/tasks/uninstall.yaml
  tags:
  - uninstall-elasticsearch

- name: Uninstall Fluentd
  hosts: primary-master
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - import_tasks: roles/fluentd/tasks/uninstall.yaml
  tags:
  - uninstall-fluentd

- name: Clean up Elasticsearch and fluentd data
  hosts: nodes
  remote_user: root
  gather_facts: no
  any_errors_fatal: yes
  tasks:
  - shell: "rm -rf /var/log/fluentd-buffers /var/lib/es/*"
    args:
      warn: no
  tags:
  - cleanup-data