#
# Set up Kibana as frontend for Elasticsearch
#
---
- name: Create directory for Kibana installation
  file: "path=/root/setup/kibana mode=0755 state=directory"

- name: Copy Kibana yaml files
  copy: "src={{ item }} dest=/root/setup/kibana/"
  with_items:
  - kibana-deployment.yaml
  - kibana-service.yaml

- name: Install Kibana
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl create -f /root/setup/kibana/"